# workaround for vagrant-share error: vagrant plugin install vagrant-share --plugin-version 1.1.8 (from https://github.com/mitchellh/vagrant/issues/8519)
#
# then vagrant up
#

nodes = [
  { :hostname => 'server', :ip => '192.168.33.15', :box => 'bento/centos-7.3', :ram => 1024 }, # has VB guest additions
  { :hostname => 'client', :ip => '192.168.33.10', :box => 'centos/7', :ram => 1024 }, # is configured for net.ifnames=0
]

Vagrant.configure(2) do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.provider "virtualbox"
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :private_network, ip: node[:ip]
      nodeconfig.ssh.insert_key = false
      nodeconfig.vm.synced_folder ".", "/vagrant", disabled: true
      nodeconfig.vm.provision :shell, path: "provision-centos7.sh"
    end
  end

  # server should
  # * expose isos dir from host
  # * build and host the RPMs
  config.vm.define "server" do |nodeconfig|
    nodeconfig.vm.synced_folder "isos/", "/isos", owner: "root", group: "root"
    nodeconfig.vm.synced_folder "../src", "/src"
    nodeconfig.vm.provision :shell, path: "provision-centos7-server.sh", run: "always"
  end

  config.vm.define "client" do |nodeconfig|
    nodeconfig.vm.provision :shell, path: "provision-centos7-client.sh", run: "always"
  end

  config.vm.define "recover", autostart: false do |recover|
    recover.vm.box = "clink15/pxe"
    recover.vm.boot_timeout = 3600
    recover.ssh.insert_key = false
    # Vagrant wants an IP, but ReaR will configure it
    recover.vm.network :private_network, ip: "192.168.33.10", auto_config: false
    # Folder sync doesn't work in rescue image
    recover.vm.synced_folder ".", "/vagrant", disabled: true
    recover.ssh.username = "root" # we added the vagrant insecure key to root in the client

    recover.vm.provider :virtualbox do |recover_prov|
      recover_prov.name = "recover"
      recover_prov.gui = true unless ENV['NO_GUI']
      recover_prov.memory = "1024"
      recover_prov.cpus = "1"

      # https://docs.vagrantup.com/v2/virtualbox/configuration.html
      # http://superuser.com/questions/741734/virtualbox-how-can-i-add-mount-an-iso-image-file-from-command-line
      # make sure file "/export/isos/client/rear-client.iso" is readable by others
      # According URL https://github.com/mitchellh/vagrant/issues/8105 "IDE Controller" might be "IDE" only
      recover_prov.customize ["storageattach", :id, "--storagectl", "IDE",
                              "--port", "0", "--device", "1", "--type", "dvddrive",
                              "--medium", "isos/client/rear-client.iso"]
      recover_prov.customize ["modifyvm", :id, "--boot1", "DVD", "--boot2", "disk",
                              "--boot3", "none", "--boot4", "none"]
      end
    end
end

# -*- mode: ruby -*-
# vi: set ft=ruby